"""added isAdmin to users

Revision ID: 3b95be865b3c
Revises: cb49abf9ff8b
Create Date: 2026-02-01 23:56:29.742746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b95be865b3c'
down_revision: Union[str, None] = 'cb49abf9ff8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate_limit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_rate_limit_logs_userId')

    op.drop_table('rate_limit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isAdmin', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET \"isAdmin\" = false WHERE \"isAdmin\" IS NULL")
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('isAdmin', existing_type=sa.Boolean(), nullable=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('isAdmin')

    op.create_table('rate_limit_logs',
    sa.Column('userId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('messageCount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='rate_limit_logs_userId_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='rate_limit_logs_pkey')
    )
    with op.batch_alter_table('rate_limit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_rate_limit_logs_userId', ['userId'], unique=False)

    # ### end Alembic commands ###
