"""added userLastEditMessageId prop to message mapping

Revision ID: 828c363b0e62
Revises: 3b95be865b3c
Create Date: 2026-02-02 00:43:16.044063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '828c363b0e62'
down_revision: Union[str, None] = '3b95be865b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userLastEditMessageId', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_message_mappings_userLastEditMessageId'), ['userLastEditMessageId'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_mappings_userLastEditMessageId'))
        batch_op.drop_column('userLastEditMessageId')

    # ### end Alembic commands ###
