"""test

Revision ID: cb49abf9ff8b
Revises: 
Create Date: 2026-02-01 23:39:15.683091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb49abf9ff8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate_limit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_rate_limit_logs_userId')

    op.drop_table('rate_limit_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_logs',
    sa.Column('userId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('messageCount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='rate_limit_logs_userId_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='rate_limit_logs_pkey')
    )
    with op.batch_alter_table('rate_limit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_rate_limit_logs_userId', ['userId'], unique=False)

    # ### end Alembic commands ###
