from enum import Enum

class ErrorCodeEnum(Enum):
    GENERAL_ERROR = "ERROR"
    TG_API_ERROR = "TG_API_ERROR"
    DB_ERROR = "DB_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
    SERVICE_ERROR = "SERVICE_ERROR"
    CALLBACK_ERROR = "CALLBACK_ERROR"
    MESSAGE_ERROR = "MESSAGE_ERROR"
    DELETE_ERROR = "DELETE_ERROR"
    EDIT_ERROR = "EDIT_ERROR"
    SILENT_ERROR = "SILENT_ERROR"
    UNHANDLED_ERROR = "UNHANDLED_ERROR"
